# Generated by Django 4.2.14 on 2024-09-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
    ]
